# Leaf OS Video — configuração mínima do MediaMTX.
rtsp: true
rtspAddress: :8554
webrtc: true
webrtcAddress: :8889
webrtcLocalUDPAddress: :8189
webrtcAllowOrigins: ['*']

paths:
  rov:
    source: publisher
